/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        curDi: "#ffb300",
        rojo: "#ff1b1b",
        borderGrey: "#bec3ca",
        fieldGrey: "#f4f6fa",
        borderGrey1: "#e5e7eb",
        primary: "#2a50e8",
        myBlue: "#0d6efd",
        myBlueDark: "#055ddf",
        darkBlueBg:"#000b4e",
        myLightBlue:"#3059c9",
        primaryDark:"#000b4e",
        myBlue:"#1e40af",
        myDarkPurple:"#1900a2",
        myPurple:"#250da7",
        myPurple2:"#2000d1",
        myLightPurple:"#321cac",
        myGrey:"#c2c8f9",
      },
      screens: {
        "nav-bar": { max: "1377px" },
        "program-selector": { max: "859px" },
        "beneficios": { max: "900px" },
        "beneficios1": { max: "552px" },
        "firstBanner": { max: "1350px" },
        "firstBanner1": { max: "1261px" },
        "secondBanner": { max: "750px" },
        "mob-last": { max: "376px" },
        "mob-first": { max: "500px" },
        "mob-first": { max: "500px" },
        "videoMain": { max: "690px" },
        "certificacionIso": { max: "639px" },
        "videoMain2": { max: "427px" },
        "estamosEnLinea": { max: "1257px" },
        "estamosEnLinea2": { max: "1060px" },
        "estamosEnLinea3": { max: "386px" },
        "inHouseBanner": { max: "1239px" },
        "inHouseBanner2": { max: "431px" },
        "listaDeProgramas": { max: "999px" },
        "listaDeProgramas1": { max: "500px" },
        "myButtons": { max: "655px" },
        "soliciteUna": { max: "1285px" },
        "soliciteUna1": { max: "723px" },
        "mob": { max: "500px" },
        "másde14,000alumnoscapacitados": { max: "853px" },
        "popUp":{max:"1211px"},
        "flexContainer":{max:"611px"},
        "contactenosBanner":{max:"1048px"},
        "nosotros":{max:"729px"}
      },
    },
  },
  plugins: [],
};
